path: taxdump/canidae_rosales
out: taxdump/combined/canidae_rosales
taxonomy_format: ncbi
root_taxon_id:
  - 9608
  - 3744
base_taxon_id: 2759
name_classes:
  - scientific name
  - synonym
xref_label: ncbi
taxonomies:
  - path: taxdump/gbif/simple.txt
    taxonomy_format: gbif
    root_taxon_id:
      - root
    base_taxon_id: root
    name_classes:
      - scientific name
    xref_label: gbif
