on:
  workflow_call:
    inputs:
      rust_directory:
        required: false
        type: string
        default: ./rust
      target:
        required: false
        type: string
        default: x86_64-unknown-linux-gnu
      artifact_name:
        required: false
        type: string
        default: binaries-linux
      output_name:
        required: false
        type: string
        default: blobtk-linux
      rust_toolchain:
        required: false
        type: string
        default: "1.91.0"
      rustflags:
        required: false
        type: string
        default: "-C target-feature=+crt-static -C relocation-model=static"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ${{ inputs.rust_directory }}/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('rust/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install static libraries for C
        run: |
          sudo apt-get update
          sudo apt-get install -y libc6-dev
      - name: Install OpenSSL build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pkg-config libssl-dev perl
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ inputs.rust_toolchain }}
          targets: ${{ inputs.target }}
      - name: Build
        working-directory: ${{ inputs.rust_directory }}
        run: |
          RUSTFLAGS="${{ inputs.rustflags }}" cargo build --target ${{ inputs.target }} --release
      - name: Rename binary
        run: |
          mv ${{ inputs.rust_directory }}/target/${{ inputs.target }}/release/blobtk ${{ inputs.rust_directory }}/target/release/${{ inputs.output_name }}
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.rust_directory }}/target/release/${{ inputs.output_name }}*
